[general]
email = "patrick.hayes@aurecongroup.com"

[browser]
gatherUsageStats = false

[server]
port = 8502
address = "localhost"
headless = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
